### ISSUE TITLE
Два элемента FORM при тесте компонента Login

### ISSUE THREAD

**Issue by mkremnev** [altsioma/otus-lessons#28]
[В тесте](https://github.com/altsioma/otus-lessons/blob/master/src/components/Auth.test.tsx) используется монтирование компонента Login, который представляет собой 2 styled компонента [Form ](https://github.com/altsioma/otus-lessons/blob/master/src/components/Form/Form.styled.tsx) поэтому при использовании метода jest component.find находится 2 ноды.
Можно использовать:
`wrapper.find('form').at(number_node).simulate('submit', { preventDefault: () => null });`

**Comment by altsioma** [comment]
Dead code. Это был неиспользуемый тест после рефакторинга, удалил.
